spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.36.79:3306/deat4
    username: root
    password: 123456
    #失效时间
  session:
    timeout: 86400
